### ISSUE TITLE
Thanks for your sharing but info and pictures on Advanced Rework forum are gone

### ISSUE THREAD

**Issue by protocold** [ayilm1/gMUXBypass#1]
At the moment it seems like advancedreworks site is dead. 

Can you possibly put up the instruction/pictures in a doc in this repo? This would help many of us!

Thank you so much!

**Comment by ayilm1** [comment]
I can move the write-up to the readme, but I don't have time right now. For the time being, here is the via location - 6.37mm from the right, 2.61mm from the bottom.
![20200615_090247](https://user-images.githubusercontent.com/2467074/88465328-743a8600-cf05-11ea-96eb-e97d90d71e3b.jpg)

**Comment by protocold** [comment]
can you also include what we need to remove from the board temporarily again? google cache is now gone.

**Comment by ayilm1** [comment]
Damn, that's a shame. I should have saved the cached version so I didn't have to write everything from scratch again. Oh well, guess I'll have to. As for the inductor you need remove - that's L2406. Removing it keeps the PCH from starting up and consequently clamping the JTAG clock line. Remove it temporarily if you have issues programming the FPGA.

**Comment by protocold** [comment]
sorry to be a noob, but to clarify do we plug the magsafe or not?

**Comment by ayilm1** [comment]
Doesn't matter. As long as it's powered.

**Comment by protocold** [comment]
ok i take it as you mean the macbook is powered, either by battery or magsafe?

**Comment by ayilm1** [comment]
It does matter how you power the machine. As long as it's powered and the FPGA has its 3.3V IO and 1.2V core voltages.

**Comment by protocold** [comment]
Did you use a file or something to expose the via? What's the best way to do so?

**Comment by ayilm1** [comment]
whatever you have on hand that's fine and sharp. A file will mangle this. Would not recommend. I used a scalpel and a hypodermic needle tip.
