### ISSUE TITLE
Displayport output ?

### ISSUE THREAD

**Issue by roddoart** [ayilm1/gMUXBypass#10]
Hi All,
looking again to the FPGA design and the schematics to answer feedbacks in issue #8, I see that the 2 signals that control the DP multiplexer are not driven at all. Electrically speaking, I see no reason why we could not configure the DP Mux (U9220) to route the Integrated Graphics DP up to the DP connector.
Is someone aware of any software restrictions that prevent it ? Maybe the kext file is not activating properly the DP_IG_xxx lines ?
We could try a new FPGA design that control this mux to re-enable the DP output ?
Any advices here ? (my knowledge of the software side is limited)
Thanks :-)

**Comment by richardstefun** [comment]
That sounds interesting. Does it mean that the internal screen would be disabled while using external display?

**Comment by roddoart** [comment]
I don't think so. LVDS and DP are separate buses.

**Comment by roddoart** [comment]
Hmm, I found the answer here : 
https://github.com/torvalds/linux/blob/master/drivers/platform/x86/apple-gmux.c
(our linux friends already studied that)
 * The external DP port is only fully switchable on the first two unibody
 * MacBook Pro generations, MBP5 2008/09 and MBP6 2010. This is done by an
 * `NXP CBTL06141`_ which is controlled by gmux. It's the predecessor of the
 * eDP mux on retinas, the difference being support for 2.7 versus 5.4 Gbit/s.
 *
 * The following MacBook Pro generations replaced the external DP port with a
 * combined DP/Thunderbolt port and lost the ability to switch it between GPUs,
 * connecting it either to the discrete GPU or the Thunderbolt controller.
 * Oddly enough, while the full port is no longer switchable, AUX and HPD
 * are still switchable by way of an `NXP CBTL03062`_ (on pre-retinas
 * MBP8 2011 and MBP9 2012) or two `TI TS3DS10224`_ (on retinas) under the
 * control of gmux. Since the integrated GPU is missing the main link,
 * external displays appear to it as phantoms which fail to link-train.
 
So forget my comment. Issue can be closed.

**Comment by roddoart** [comment]
irrelevant topic
