### ISSUE TITLE
Screen flickers from wake

### ISSUE THREAD

**Issue by Shredplayer** [ayilm1/gMUXBypass#3]
Prior to gMUX programming on the board i used NVRAM to bypass and screen don't flicker when waking up the machine but after gMUX proramming the screen flickers for a moment when waking up, tried both variants andt same issue.

**Comment by ayilm1** [comment]
Why did you try both variants? One is for people that carry out the wire mod, The other is for people who don't and want to use a software-based screen 'dimmer'. Have you done the wire mod on yours?

**Comment by Shredplayer** [comment]
I did install the 1st variant just to test and flickers, i then decided to do the hardware mod with the 2nd variant and i did enable native brightness but it still flickers from wake, flickers only within a second and after that no more flickers, just the instance from waking up, nvram technique do not have this issue.

**Comment by ayilm1** [comment]
Unfortunately I haven't observed this problem on my system. Wake is a quick ramp up in brightness. I don't believe any of the others who have applied this FPGA configuration have reported the issue either. There is another config file (.jedec) floating around on a Russian forum somewhere. I believe this just writes the PWM pin high. So if you want to test with this file, I would disconnect the wire else you might damage the PCH output driver. You won't get brightness control with this, however it gives you another data point. It's highly unlikely it's the code if you have the same issue with two independent codebases.

**Comment by ayilm1** [comment]
Just a heads up. I'll be closing this issue after 30 days since there hasn't been any activity and assume your issue was fixed.
